#include "bootpack.h"

/**
	interruption initialization and handling
*/
void init_pic(void)
/* PIC(programmable interrupt controller) initialization */
{
	/* PIC0: master PIC, PIC1: slave PIC */
	/* IMR: interrupt mast register */
	io_out8(PIC0_IMR,  0xff  ); /* mask all interruptions for master PIC */
	io_out8(PIC1_IMR,  0xff  ); /* mask all interruptions for slave PIC */

	io_out8(PIC0_ICW1, 0x11  ); /* edge trigger mode */
	io_out8(PIC0_ICW2, 0x20  ); /* IRQ0-7 will be mapped for INT20-27 */
	io_out8(PIC0_ICW3, 1 << 2); /* PIC1 ised connected from IRQ2, IRQ: interruption request from devices */
								/* PIC0 leads: 11111011, the second lead is used for connecting to PIC1 */
	io_out8(PIC0_ICW4, 0x01  ); /* no buffer mode */

	io_out8(PIC1_ICW1, 0x11  ); /* edge trigger mode */
	io_out8(PIC1_ICW2, 0x28  ); /* IRQ8-15 will be mapped for INT28-2f */
	io_out8(PIC1_ICW3, 2     ); /* PIC1 ised connected from IRQ2 */
	io_out8(PIC1_ICW4, 0x01  ); /* no buffer mode */

	io_out8(PIC0_IMR,  0xfb  ); /* 11111011 PIC1 is using IRQ2, others are masked */
	io_out8(PIC1_IMR,  0xff  ); /* 11111111 all masked */

	return;
}

/* IRQ1 : keyboard, INT21 */
void inthandler21(int *esp)
{
	struct BOOTINFO *binfo = (struct BOOTINFO *) ADR_BOOTINFO;
	boxfill8(binfo->vram, binfo->scrnx, COL8_000000, 0, 0, 32 * 8 - 1, 15);
	putfonts8_asc(binfo->vram, binfo->scrnx, 0, 0, COL8_FFFFFF, "INT 21 (IRQ-1 : PS/2 keyboard");
	for(;;) {
		io_hlt();
	}
}

/* IRQ12 ： mouse, INT12 */
void inthandler2c(int *esp)
{
	struct BOOTINFO *binfo = (struct BOOTINFO *) ADR_BOOTINFO;
	boxfill8(binfo->vram, binfo->scrnx, COL8_000000, 0, 0, 32 * 8 - 1, 15);
	putfonts8_asc(binfo->vram, binfo->scrnx, 0, 0, COL8_FFFFFF, "INT 2C (IRQ-12) : PS/2 mouse");
	for (;;) {
		io_hlt();
	}
}

/* IRQ7 : INT 27 generated by PIC initialization */
void inthandler27(int *esp)
{
	io_out8(PIC0_OCW2, 0x67); 
	return;
}
