#include "bootpack.h"

/**
	interruption initialization and handling
*/
void init_pic(void)
/* PIC(programmable interrupt controller) initialization */
{
	/* PIC0: master PIC, PIC1: slave PIC */
	/* IMR: interrupt mast register */
	io_out8(PIC0_IMR,  0xff  ); /* mask all interruptions for master PIC */
	io_out8(PIC1_IMR,  0xff  ); /* mask all interruptions for slave PIC */

	io_out8(PIC0_ICW1, 0x11  ); /* edge trigger mode */
	io_out8(PIC0_ICW2, 0x20  ); /* IRQ0-7 will be mapped for INT20-27 */
	io_out8(PIC0_ICW3, 1 << 2); /* PIC1 ised connected from IRQ2, IRQ: interruption request from devices */
								/* PIC0 leads: 11111011, the second lead is used for connecting to PIC1 */
	io_out8(PIC0_ICW4, 0x01  ); /* no buffer mode */

	io_out8(PIC1_ICW1, 0x11  ); /* edge trigger mode */
	io_out8(PIC1_ICW2, 0x28  ); /* IRQ8-15 will be mapped for INT28-2f */
	io_out8(PIC1_ICW3, 2     ); /* PIC1 ised connected from IRQ2 */
	io_out8(PIC1_ICW4, 0x01  ); /* no buffer mode */

	io_out8(PIC0_IMR,  0xfb  ); /* 11111011 PIC1 is using IRQ2, others are masked */
	io_out8(PIC1_IMR,  0xff  ); /* 11111111 all masked */

	return;
}

struct KEYBUF keybuf;

/* IRQ1 : keyboard, INT21 */
/* note we're just buffering the key value here to process faster, there's a loop in bootpack.c to check the buffer and print it */
void inthandler21(int *esp)
{
	unsigned char data;
	/* need to do OUT io to inform this interruption is already consumed, otherwise PIC will not continue listen to further interruption */
	io_out8(PIC0_OCW2, 0x61);
	/* then get key data from keyboard port */
	data = io_in8(PORT_KEYDAT);
	/*
	if(keybuf.flag == 0) {
		keybuf.data = data;
		keybuf.flag = 1;
	}
	*/
	/* try to add the value to end of the ring buffer */
	/* using a fancier ring buffer */
	if(!keybuf.full) {
		keybuf.data[keybuf.end] = data;
		keybuf.end = (keybuf.end + 1) % 32;
		if(keybuf.end == keybuf.start) {
			keybuf.full = 1;
		}
	}

	/* if end is equal or after start */
	/*
	if(keybuf.end >= keybuf.start && !keybuf.full) {
		if(keybuf.end + 1 < 32) {
			keybuf.data[keybuf.end++] = data;
		} 
		 ;else we add from start of the buffer - we only add when there's still empty spot in the 32 length array
		else if(keybuf.start > 0){
			keybuf.end = 0;
			keybuf.data[0] = data;
		}
	} 
	 ;if end is before start - we only add when there's still empty spot in the 32 length array 
	else if(keybuf.end < keybuf.start){
		keybuf.data[keybuf.end++] = data;
	}
	if(keybuf.end == keybuf.start) {
		keybuf.full = 1;
	}
	*/

	/*
	struct BOOTINFO *binfo = (struct BOOTINFO *) ADR_BOOTINFO;
	sprintf(s, "%02x", data);

	boxfill8(binfo->vram, binfo->scrnx, COL8_008484, 0, 16, 15, 31);
	putfonts8_asc(binfo->vram, binfo->scrnx, 0, 16, COL8_FFFFFF, s);
	*/
	return;
}

/* IRQ12 ： mouse, INT12 */
void inthandler2c(int *esp)
{
	struct BOOTINFO *binfo = (struct BOOTINFO *) ADR_BOOTINFO;
	boxfill8(binfo->vram, binfo->scrnx, COL8_000000, 0, 0, 32 * 8 - 1, 15);
	putfonts8_asc(binfo->vram, binfo->scrnx, 0, 0, COL8_FFFFFF, "INT 2C (IRQ-12) : PS/2 mouse");
	for (;;) {
		io_hlt();
	}
}

/* IRQ7 : INT 27 generated by PIC initialization */
void inthandler27(int *esp)
{
	io_out8(PIC0_OCW2, 0x67); 
	return;
}
